=== USNavalResearchLaboratory/GeoIPS/geoips/geoimg/xml_palettes/colorbars.dtd
<!ELEMENT colorbar_list     (colorbar+)>
<!ELEMENT colorbar          (min_val,max_val,transition+)>
<!ELEMENT transition        (start_color,end_color,start_val,end_val)>
<!-- colors specified as 
        colorname           pink, red, blue, etc
        R G B               0 100 200 (0 to 255)
        R G B               0 .1  .8 (0 to 1)
-->
<!ELEMENT start_color       (#PCDATA)>
<!ELEMENT end_color         (#PCDATA)>
<!ELEMENT start_val         (#PCDATA)>
<!ELEMENT end_val           (#PCDATA)>
<!-- Must cover entire range from min_val to max_val in the 
        specified transitions
-->
<!ELEMENT min_val         (#PCDATA)>
<!ELEMENT max_val           (#PCDATA)>

<!ATTLIST colorbar name CDATA #REQUIRED>
<!ATTLIST colorbar arg CDATA "no">
<!ATTLIST colorbar_list xmlns:py CDATA #REQUIRED>

=== USNavalResearchLaboratory/GeoIPS/geoips/geoimg/xml_palettes/wv_so1.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE colorbar_list SYSTEM "colorbars.dtd">

<colorbar_list xmlns:py="http://codespeak.net/lxml/objectify/pytype">
    <colorbar name="wv_so1">
        <!-- 
            min and max vals can be any values, 
            start and end vals in transitions below must fill the entire range.
                The first specified start_val MUST equal min_val
                The last specified end_val MUST equal max_val
        -->
        <min_val>200</min_val>
        <max_val>270</max_val>
        <transition>
            <!-- 
                start_color and end_color can be any matplotlib supported color value.
                http://matplotlib.org/api/colors_api.html
                Test using color full or abbreviated names: 
                    pink = (1,.75,.8)
                    r = red = (1,0,0)
            -->
            <start_color>#006400</start_color>
            <end_color>#228B22</end_color>
            <start_val>200</start_val>
            <end_val>210</end_val>
        </transition>
        <transition>
            <!-- 
                Test colors using tuples
                    (0,.5,0) =~ Green
                or RGB hex specification
                    #0000FF = Blue
            -->
            <start_color>#228B22</start_color>
            <end_color>#40E0D0</end_color>
            <start_val>210</start_val>
            <end_val>220</end_val>
        </transition>
        <transition>
            <!-- 
                Test colors using tuples
                    (0,.5,0) =~ Green
                or RGB hex specification
                    #0000FF = Blue
            -->
            <start_color>(0,.5,0.5)</start_color>
            <end_color>#FF00FF</end_color>
            <start_val>220</start_val>
            <end_val>230</end_val>
        </transition>
        <transition>
            <!-- 
                Test colors using html color names
            -->
            <start_color>#FFFFFF</start_color>
            <end_color>#000080</end_color>
            <start_val>230</start_val>
            <end_val>240</end_val>
        </transition>
        <transition>
            <!-- 
                Test colors using html color names
            -->
            <start_color>#FFFF99</start_color>
            <end_color>#331900</end_color>
            <start_val>240</start_val>
            <end_val>270</end_val>
        </transition>
    </colorbar> 
</colorbar_list>

=== USNavalResearchLaboratory/GeoIPS/geoips/geoimg/xml_palettes/testcb2.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE colorbar_list SYSTEM "colorbars.dtd">

<colorbar_list xmlns:py="http://codespeak.net/lxml/objectify/pytype">
    <colorbar name="testcb2">
        <min_val>0</min_val>
        <max_val>100</max_val>
        <transition>
            <start_color>pink</start_color>
            <end_color>red</end_color>
            <start_val>0</start_val>
            <end_val>20</end_val>
        </transition>
        <transition>
            <start_color>green</start_color>
            <end_color>blue</end_color>
            <start_val>20</start_val>
            <end_val>30</end_val>
        </transition>
        <transition>
            <start_color>orange</start_color>
            <end_color>red</end_color>
            <start_val>30</start_val>
            <end_val>100</end_val>
        </transition>
    </colorbar> 
</colorbar_list>

=== USNavalResearchLaboratory/GeoIPS/geoips/geoimg/xml_palettes/wvtest2.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE colorbar_list SYSTEM "colorbars.dtd">

<colorbar_list xmlns:py="http://codespeak.net/lxml/objectify/pytype">
    <colorbar name="wvtest2">
        <min_val>-80</min_val>
        <max_val>10</max_val>
        <transition>
            <start_color>(.95,.8,1)</start_color>
            <end_color>(.2,0,.4)</end_color>
            <start_val>-80</start_val>
            <end_val>-70</end_val>
        </transition>
        <transition>
            <start_color>(1,0,0)</start_color>
            <end_color>(1,1,0)</end_color>
            <start_val>-70</start_val>
            <end_val>-64</end_val>
        </transition>
        <transition>
            <start_color>(1,1,0)</start_color>
            <end_color>(0,1,0)</end_color>
            <start_val>-64</start_val>
            <end_val>-59</end_val>
        </transition>
        <transition>
            <start_color>(0,1,0)</start_color>
            <end_color>(0,0,.8)</end_color>
            <start_val>-59</start_val>
            <end_val>-55</end_val>
        </transition>
        <transition>
            <start_color>(0,0,.8)</start_color>
            <end_color>(1,1,1)</end_color>
            <start_val>-55</start_val>
            <end_val>-50</end_val>
        </transition>
        <transition>
            <start_color>(1,1,1)</start_color>
            <end_color>(.1,.1,.1)</end_color>
            <start_val>-50</start_val>
            <end_val>-40</end_val>
        </transition>
        <transition>
            <start_color>(.1,.1,.1)</start_color>
            <end_color>(.6,.3,0)</end_color>
            <start_val>-40</start_val>
            <end_val>-32</end_val>
        </transition>
        <transition>
            <start_color>(.6,.3,0)</start_color>
            <end_color>(1,.5,0)</end_color>
            <start_val>-32</start_val>
            <end_val>-29</end_val>
        </transition>
        <transition>
            <start_color>(1,.5,0)</start_color>
            <end_color>(.3,.3,0)</end_color>
            <start_val>-29</start_val>
            <end_val>-20</end_val>
        </transition>
        <transition>
            <start_color>(.3,.3,0)</start_color>
            <end_color>(.9,.9,0)</end_color>
            <start_val>-20</start_val>
            <end_val>-12</end_val>
        </transition>
        <transition>
            <start_color>(.9,.9,0)</start_color>
            <end_color>(.5,.3,.5)</end_color>
            <start_val>-12</start_val>
            <end_val>-8</end_val>
        </transition>
        <transition>
            <start_color>(.5,.3,.5)</start_color>
            <end_color>(1,.3,.3)</end_color>
            <start_val>-8</start_val>
            <end_val>0</end_val>
        </transition>
        <transition>
            <start_color>(1,.3,.3)</start_color>
            <end_color>(.3,.1,.1)</end_color>
            <start_val>0</start_val>
            <end_val>10</end_val>
        </transition>
    </colorbar> 
</colorbar_list>

=== USNavalResearchLaboratory/GeoIPS/geoips/geoimg/xml_palettes/testcb.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE colorbar_list SYSTEM "colorbars.dtd">

<colorbar_list xmlns:py="http://codespeak.net/lxml/objectify/pytype">
    <colorbar name="testcb">
        <!-- 
            min and max vals can be any values, 
            start and end vals in transitions below must fill the entire range.
                The first specified start_val MUST equal min_val
                The last specified end_val MUST equal max_val
        -->
        <min_val>0</min_val>
        <max_val>100</max_val>
        <transition>
            <!-- 
                start_color and end_color can be any matplotlib supported color value.
                http://matplotlib.org/api/colors_api.html
                Test using color full or abbreviated names: 
                    pink = (1,.75,.8)
                    r = red = (1,0,0)
            -->
            <start_color>pink</start_color>
            <end_color>r</end_color>
            <start_val>0</start_val>
            <end_val>20</end_val>
        </transition>
        <transition>
            <!-- 
                Test colors using tuples
                    (0,.5,0) =~ Green
                or RGB hex specification
                    #0000FF = Blue
            -->
            <start_color>(0,.5,0)</start_color>
            <end_color>#0000FF</end_color>
            <start_val>20</start_val>
            <end_val>30</end_val>
        </transition>
        <transition>
            <!-- 
                Test colors using html color names
            -->
            <start_color>burlywood</start_color>
            <end_color>chartreuse</end_color>
            <start_val>30</start_val>
            <end_val>100</end_val>
        </transition>
    </colorbar> 
</colorbar_list>
