=== USNavalResearchLaboratory/GeoIPS/geoips/productfiles/productfiles.dtd
<!--
# Author:
#    Naval Research Laboratory, Marine Meteorology Division
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the NRLMMD License included with this program.  If you did not
# receive the license, see http://www.nrlmry.navy.mil/geoips for more
# information.
#
# This program is distributed WITHOUT ANY WARRANTY; without even the implied
# warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# included license for more details.
-->
<!ELEMENT product_file          (product+)>
<!ELEMENT product               (multisource_args?, contour_args?, windbarbs_args?, streamline_args?, basic_args?, external_args?, externalalg_args?, footprints_args?, rgb_args?)>
<!-- multisource product type is special. Order matters for productlayer
        Specify order in in productlayer attribute. Smallest number
            for order is on the top, largest number is on the bottom.
        One or more sourcelayer
     Also specify hour range to match (must be integer value), default to 2h when not specified
     Also specify whether to match one (default) or all files in range (matchall = 'yes' to match all)  -->
<!ELEMENT multisource_args         (productlayer+, min_cover?, colorbar*,legend_text?,  coastcolor?, gridcolor?)>
<!ELEMENT productlayer          (possiblesource+)>


<!ELEMENT contour_args          (source+, dataset?, img1?, img2?, img3?, img4?, img5?, img6?, img7?,img8?, day_night,min_cover?, interpmethod?, cmap, interpolation_radius_of_influence?, max_day_zen_ang?, min_ngt_zen_ang?,
                                 colorbar?,legend_text?, coastcolor?, gridcolor?,best_possible_pixel_height?,
                                 best_possible_pixel_width?)>
<!ELEMENT basic_args            (source+, dataset?, img, day_night,min_cover?, interpmethod?, cmap, interpolation_radius_of_influence?, max_day_zen_ang?, min_ngt_zen_ang?,
                                 colorbar?,legend_text?, coastcolor?, gridcolor?,best_possible_pixel_height?,
                                 best_possible_pixel_width?)>
<!ELEMENT windbarbs_args        (source+, dataset?, img, img1, day_night,min_cover?, interpmethod?, cmap,interpolation_radius_of_influence?,  max_day_zen_ang?, min_ngt_zen_ang?,
                                 colorbar?,legend_text?, coastcolor?, gridcolor?,best_possible_pixel_height?,
                                 best_possible_pixel_width?)>
<!ELEMENT streamline_args       (source+, dataset?, img, img1, day_night,min_cover?, interpmethod?, cmap,interpolation_radius_of_influence?,  max_day_zen_ang?, min_ngt_zen_ang?,
                                 colorbar?,legend_text?, coastcolor?, gridcolor?,best_possible_pixel_height?,
                                 best_possible_pixel_width?)>
<!ELEMENT footprints_args       (source+, dataset?, speed, direction, day_night,min_cover?, interpmethod?, cmap,interpolation_radius_of_influence?,  max_day_zen_ang?, min_ngt_zen_ang?,
                                 colorbar?,legend_text?, coastcolor?, gridcolor?,best_possible_pixel_height?,
                                 best_possible_pixel_width?)>
<!ELEMENT external_args         (source+, dataset?, datasets?, day_night?,min_cover?,interpmethod?, interpolation_radius_of_influence?, colorbar*,legend_text?, max_day_zen_ang?,
                                 coastcolor?, gridcolor?, best_possible_pixel_height?,best_possible_pixel_width?)>
<!ELEMENT externalalg_args         (source+, dataset?, datasets?, day_night?,min_cover?,interpmethod?, cmap?, interpolation_radius_of_influence?, colorbar*,legend_text?, max_day_zen_ang?, min_ngt_zen_ang?,
                                 coastcolor?, gridcolor?, best_possible_pixel_height?,best_possible_pixel_width?)>
<!ELEMENT rgb_args              (source+, dataset?, red, grn, blu, day_night,min_cover?,interpmethod?, interpolation_radius_of_influence?, max_day_zen_ang?, min_ngt_zen_ang?, coastcolor?,
                                 gridcolor?,best_possible_pixel_height?,best_possible_pixel_width?)>
<!ELEMENT legend_text           (below_colorbars?,above_colorbars?,below_title?)>
<!ELEMENT below_colorbars       (#PCDATA)>
<!ELEMENT above_colorbars       (#PCDATA)>
<!ELEMENT below_title           (#PCDATA)>
<!ELEMENT interpolation_radius_of_influence (#PCDATA)>
<!ELEMENT interpmethod          (#PCDATA)>

<!ELEMENT source                (var+, gvar*)>
<!ELEMENT datasets              (dataset+)>
<!ELEMENT var                   (#PCDATA)>

<!-- Used to specify possible sources for a specific product layer in multisource products-->
<!ELEMENT possiblesource        (#PCDATA)>

<!-- I think gvar is deprecated (set zenith='yes' on specific variable to use SunZenith, Lat/Lon use is assumed)
        but it still exists in some productfiles, so leave for now -->
<!ELEMENT gvar                  (#PCDATA)>
<!ELEMENT dataset               (#PCDATA)>
<!ELEMENT equation              (#PCDATA)>

<!ELEMENT range                 (min_value, max_value, outbounds?,min_outbounds?,max_outbounds?,normalize?,inverse?, units)>
<!-- Equation range paramaters are executed in this order, if specified:
    inverse 
    min_value
    max_value
    normalize
min_outbounds/max_outbounds is used in apply_minimum_value, apply_maximum_value, and normalize. Options are:
If outbounds is set, it's value is used for both min_outbounds and max_outbounds (if they are not set)
    'crop' DEFAULT (set in geoimg/geoimg.py.apply_data_range, productfile/xml.py.outbounds
    'mask'
    'retain'


    units is currently UNUSED. Has not been implemented
-->
<!ELEMENT min_value             (#PCDATA)>
<!ELEMENT max_value             (#PCDATA)>
<!ELEMENT outbounds             (#PCDATA)>
<!ELEMENT min_outbounds         (#PCDATA)>
<!ELEMENT max_outbounds         (#PCDATA)>
<!ELEMENT units                 (#PCDATA)>
<!ELEMENT normalize             (#PCDATA)>
<!ELEMENT inverse               (#PCDATA)>


<!ELEMENT beamwidth             (#PCDATA)>
<!ELEMENT day_night             (#PCDATA)>
<!ELEMENT min_cover             (#PCDATA)>
<!ELEMENT colorbar              (cmap, ticks, ticklabels?, title?, bounds?, norm?)>
<!ELEMENT cmap                  (#PCDATA)>
<!ELEMENT ticks                 (#PCDATA)>
<!ELEMENT ticklabels            (#PCDATA)>
<!ELEMENT title                 (#PCDATA)>
<!ELEMENT coastcolor            (#PCDATA)>
<!ELEMENT gridcolor             (#PCDATA)>
<!ELEMENT max_day_zen_ang       (#PCDATA)>
<!ELEMENT min_ngt_zen_ang       (#PCDATA)>
<!ELEMENT img                   (source?,equation+, color?, level?, range, gamma1?, gamma2?, best_possible_pixel_height?,
                                 best_possible_pixel_width?)>
<!ELEMENT img1                  (source?,equation+, color?, level?, range, gamma1?, gamma2?, best_possible_pixel_height?,
                                 best_possible_pixel_width?)>
<!ELEMENT img2                  (source?,equation+, color?, level?, range, gamma1?, gamma2?, best_possible_pixel_height?,
                                 best_possible_pixel_width?)>
<!ELEMENT img3                  (source?,equation+, color?, level?, range, gamma1?, gamma2?, best_possible_pixel_height?,
                                 best_possible_pixel_width?)>
<!ELEMENT img4                  (source?,equation+, color?, level?, range, gamma1?, gamma2?, best_possible_pixel_height?,
                                 best_possible_pixel_width?)>
<!ELEMENT img5                  (source?,equation+, color?, level?, range, gamma1?, gamma2?, best_possible_pixel_height?,
                                 best_possible_pixel_width?)>
<!ELEMENT img6                  (source?,equation+, color?, level?, range, gamma1?, gamma2?, best_possible_pixel_height?,
                                 best_possible_pixel_width?)>
<!ELEMENT img7                  (source?,equation+, color?, level?, range, gamma1?, gamma2?, best_possible_pixel_height?,
                                 best_possible_pixel_width?)>
<!ELEMENT img8                  (source?,equation+, color?, level?, range, gamma1?, gamma2?, best_possible_pixel_height?,
                                 best_possible_pixel_width?)>
<!ELEMENT speed                 (equation+, range, gamma1?, gamma2?, best_possible_pixel_height?,
                                 best_possible_pixel_width?)>
<!ELEMENT direction             (equation+, range, gamma1?, gamma2?, best_possible_pixel_height?,
                                 best_possible_pixel_width?)>
<!ELEMENT red                   (source?,equation+, range, gamma1?, gamma2?, best_possible_pixel_height?,
                                 best_possible_pixel_width?)>
<!ELEMENT grn                   (source?,equation+, range, gamma1?, gamma2?, best_possible_pixel_height?,
                                 best_possible_pixel_width?)>
<!ELEMENT blu                   (source?,equation+, range, gamma1?, gamma2?, best_possible_pixel_height?,
                                 best_possible_pixel_width?)>
<!ELEMENT best_possible_pixel_height    (#PCDATA)>
<!ELEMENT best_possible_pixel_width     (#PCDATA)>
<!ELEMENT color                (#PCDATA)>
<!ELEMENT level                (#PCDATA)>
<!ELEMENT gamma1                (#PCDATA)>
<!ELEMENT gamma2                (#PCDATA)>
<!ATTLIST product method        CDATA #REQUIRED>
<!ATTLIST product plotmethod    CDATA #IMPLIED>
<!-- display_name is how the product name is displayed in titles, legends, etc. Defaults to "name" if not specified.
     name is the short name for the product - used in filenames, driver calls, internal to code to reference products, etc
     finalonly specifies we should NOT produce any imagery/data in GEOIPSTEMP - really only for testing purposes (to speed 
        things up), or perhaps if we KNOW a certain product will never need any overlays (temporary imagery 
        without coastlines, gridlines, etc is required for overlays or any combined products)
-->
<!ATTLIST product name          CDATA #IMPLIED>
<!ATTLIST product finalonly     CDATA "no">
<!ATTLIST product display_name          CDATA "False">
<!ATTLIST possiblesource platforms          CDATA "False">
<!ATTLIST productlayer name          CDATA #IMPLIED>
<!ATTLIST productlayer runonreceipt      CDATA "no">
<!ATTLIST productlayer matchall      CDATA "no">
<!ATTLIST productlayer hour_range      CDATA "2">
<!-- Smallest number for order is on the top, largest number is on the bottom.-->
<!ATTLIST productlayer order    CDATA #REQUIRED>
<!ATTLIST product testonly      CDATA "no">
<!ATTLIST source name           CDATA #REQUIRED>

<!-- normalize/min/max/units/outbounds deprecated for var attlist
    zenith still used to specify solar zenith correction for specific variables
        possibly this should be specified at the equation level?
    mark_terminator allows for specifying to plot a line along the terminator,
        based on solar zenith angle.  Again, this should probably be specified 
        at the equation level ?
    eq_name used for ExternalImg types, to specify something? may or may not 
        actually be used at this point ?
-->
<!ATTLIST var zenith            CDATA "no">
<!ATTLIST var mark_terminator   CDATA "no">
<!ATTLIST var eq_name           CDATA #IMPLIED>

<!-- eq_name used when specifying multiple equations, so you can reference 
        prior equations in new calculations.
-->
<!ATTLIST equation eq_name      CDATA ''>
<!ATTLIST img cmap              CDATA ''>
<!ATTLIST speed cmap            CDATA ''>
<!ATTLIST direction cmap        CDATA ''>

=== USNavalResearchLaboratory/GeoIPS/geoips/productfiles/multisource/Low-Winds-Over-IR.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE product_file SYSTEM "../productfiles.dtd">

<!--
    Notes:
        See ../productfiles.dtd in this directory for full notes.  All DTD information
        is contained there.
-->
<product_file>
<product method='multisource' name='Low-Winds-Over-IR' testonly='yes'>
    <multisource_args>
        <productlayer name='dmvMET8IR800to950grid' order='1'>
            <possiblesource>dmv</possiblesource>
        </productlayer>
        <productlayer name='Infrared-Gray' runonreceipt='yes' order='2'>
            <possiblesource>ahi</possiblesource>
            <possiblesource>seviri</possiblesource>
            <possiblesource>abi</possiblesource>
        </productlayer>
    </multisource_args>
</product>
</product_file>

=== USNavalResearchLaboratory/GeoIPS/geoips/productfiles/abi/VIS086.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE product_file SYSTEM "../productfiles.dtd">

<!--
    Notes:
        See ../productfiles.dtd in this directory for full notes.  All DTD information
        is contained there.
-->
<product_file>
<product method='basic' name='VIS086'>
    <basic_args>
        <source name='abi'>
            <!-- Veggie band, Near-IR -->
            <var mark_terminator='yes' zenith='yes'>B03Ref</var>
        </source>
        <img>
            <equation>B03Ref</equation>
            <range>
                <min_value>0</min_value>
                <max_value>1.2</max_value>
                <units>Albedo</units>
            </range>
        </img>
        <day_night>day</day_night>
        <cmap>Greys_r</cmap>
        <colorbar>
            <cmap>Greys_r</cmap>
            <ticks>0 .2 .4 .6 .8 1.0 1.2</ticks>
            <title>0.86um, B03Ref</title>
        </colorbar>
        <coastcolor>255 175 0</coastcolor>
        <gridcolor>0 0 0</gridcolor>
    </basic_args>
</product>
</product_file>

=== USNavalResearchLaboratory/GeoIPS/geoips/productfiles/viirs/Day-Fires.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE product_file SYSTEM "../productfiles.dtd">

<!--
    Notes:
        See ../productfiles.dtd in this directory for full notes.  All DTD information
        is contained there.
-->
<product_file>
<product method='external' name='Day-Fires'>
    <external_args>
        <source name='viirs'>
            <var>SVM07Ref</var>
            <var>SVM13BT</var>
            <var>SVM15BT</var>
            <gvar>SunZenith</gvar>
        </source>
        <day_night>day</day_night>
    </external_args>
</product>
</product_file>

=== USNavalResearchLaboratory/GeoIPS/geoips/productfiles/ahi/Infrared.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE product_file SYSTEM "../productfiles.dtd">

<!--
    Notes:
        See ../productfiles.dtd in this directory for full notes.  All DTD information
        is contained there.
-->
<product_file>
<product method='basic' name='Infrared'>
    <basic_args>
        <source name='ahi'>
            <!--  4um (3.9um)  B07-->
            <!-- 11um (11.2um) B14-->
            <!-- 13um (13.3um) B16-->
            <var>B14BT</var>
        </source>
        <img>
            <equation>B14BT</equation>
            <range>
                <min_value>183.15</min_value>
                <max_value>303.15</max_value>
                <outbounds>crop</outbounds>
                <units>K</units>
            </range>
        </img>
        <day_night>both</day_night>
        <cmap>tcirRev_ascii</cmap>
        <colorbar>
            <cmap>tcirRev_ascii</cmap>
            <ticks>-90 -80 -70 -60 -50 -40 -30 -20 -10 0 10 20 30</ticks>
            <title>11um BT ($^\circ$C)</title>
        </colorbar>
        <coastcolor>255 180 0</coastcolor>
        <gridcolor>255 180 0</gridcolor>
    </basic_args>
</product>
</product_file>

=== USNavalResearchLaboratory/GeoIPS/geoips/productfiles/seviri/VIS008.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE product_file SYSTEM "../productfiles.dtd">

<!--
    Notes:
        See ../productfiles.dtd in this directory for full notes.  All DTD information
        is contained there.
-->
<product_file>
<product method="basic" name="VIS008">
    <basic_args>
        <source name='seviri'>
            <var zenith='yes'>VIS008</var>
        </source>
        <img>
            <equation>VIS008</equation>
            <range>
                <min_value>0.0</min_value>
                <max_value>100.0</max_value>
                <outbounds>crop</outbounds>
                <units>reflectance</units>
            </range>
            <gamma1>1.5</gamma1>
        </img>
        <day_night>day</day_night>
        <cmap>Greys_r</cmap>
        <coastcolor>0 0 0</coastcolor>
        <gridcolor>0 0 0</gridcolor>
    </basic_args>
</product>
</product_file>

=== USNavalResearchLaboratory/GeoIPS/geoips/productfiles/seviri/IR_087.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE product_file SYSTEM "../productfiles.dtd">

<!--
    Notes:
        See ../productfiles.dtd in this directory for full notes.  All DTD information
        is contained there.
        Arunas 20140407 varged celcius to celsius
-->
<product_file>
<product method="basic" name="IR_087">
    <basic_args>
        <source name='seviri'>
            <var>B07BT</var> <!-- 8.4um  B11 ABI   IR_087  8.7um MSG Cloud-Top Phase band, IR                                     -->
        </source>
        <img>
            <equation>B07BT</equation>
            <range>
                <min_value>183</min_value>
                <max_value>303</max_value>
                <outbounds>crop</outbounds>
                <units>kelvin</units>
            </range>
        </img>
        <day_night>both</day_night>
        <cmap>Greys</cmap>
        <colorbar>
            <cmap>Greys</cmap>
            <ticks>-90 -80 -70 -60 -50 -40 -30 -20 -10 0 10 20 30</ticks>
        </colorbar>
        <coastcolor>0 0 0</coastcolor>
        <gridcolor>0 0 0</gridcolor>
    </basic_args>
</product>
</product_file>

=== USNavalResearchLaboratory/GeoIPS/geoips/productfiles/winds/winds.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE product_file SYSTEM "../productfiles.dtd">

<!--
    Notes:
        See ../productfiles.dtd in this directory for full notes.  All DTD information
        is contained there.
-->
<product_file>
<product method='externalalg' name='winds' testonly='no'>
    <externalalg_args>
        <source name='winds'>
            <var>speed</var>
            <var>direction</var>
            <var>lats</var>
            <var>lons</var>
        </source>
        <day_night>both</day_night>
    </externalalg_args>
</product>
</product_file>

=== USNavalResearchLaboratory/GeoIPS/geoips/productfiles/modis/Night-Fires.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE product_file SYSTEM "../productfiles.dtd">

<!--
    Notes:
        See ../productfiles.dtd in this directory for full notes.  All DTD information
        is contained there.
-->
<product_file>
<product method='external' name='Night-Fires'>
    <external_args>
        <source name='modis'>
            <var>chan20.0</var>
            <var>chan31.0</var>
            <gvar>SunZenith</gvar>
        </source>
        <day_night>night</day_night>
        <coastcolor>0 180 0 255</coastcolor>
        <gridcolor>0 180 0 255</gridcolor>
    </external_args>
</product>
</product_file>
